# Generated by Django 5.0.1 on 2024-01-28 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_cabañas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabaña',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='gold_soft/static/images')),
                ('capacity', models.DateField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('id_type_cabin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipo_cabañas.tipo_cabaña')),
            ],
        ),
    ]
