# Generated by Django 4.2.1 on 2024-01-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0002_alter_cabaña_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabaña',
            old_name='id_type_cabin',
            new_name='type_cabin',
        ),
    ]
