# Generated by Django 4.2.1 on 2024-01-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0004_alter_cabaña_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabaña',
            name='type_cabin',
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
