# Generated by Django 4.2.1 on 2024-01-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0005_remove_cabaña_type_cabin_alter_cabaña_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabaña',
            name='image',
            field=models.ImageField(null=True, upload_to='cabaña_images'),
        ),
    ]
