# Generated by Django 4.2.1 on 2024-01-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabañas', '0006_alter_cabaña_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabaña',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='image',
            field=models.ImageField(null=True, upload_to='static/cabaña_images'),
        ),
        migrations.AlterField(
            model_name='cabaña',
            name='price',
            field=models.FloatField(),
        ),
    ]
